### ISSUE TITLE
Rename the script LTSP_Installer_script.sh

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#16]
Rename the script `LTSP_Installer_script.sh` to `install.sh` or `config.sh`, because it is obvious that it is a script and that it is about LTSP.

**Comment by nehajain444** [comment]
Okay... It has too much to install and less to config. So naming it install.sh
pull request - https://github.com/docker-scripts/dev--LTSP/pull/21

**Comment by dashohoxha** [comment]
I discarded  that PR. You should make another one properly, by making a git branch first.
Also it is important that you test your changes first, before committing them and making a PR.
If you don't do it, who do you think is going to test them?

**Comment by nehajain444** [comment]
okay. I tested it and make changes in the vagrant file. 
It is working now.
pull request - https://github.com/docker-scripts/dev--LTSP/pull/22
