### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#19]
Update `README.md` with installation and usage instructions.
Give some detailed instructions about how to test it as well. Suppose that the testing will be done by using another VirtualBox machine as a client.

Write any other related docs on the wiki: https://github.com/docker-scripts/dev--LTSP/wiki

**Comment by dashohoxha** [comment]
@docker-scripts/ltsp 
If you feel that instructions on README.md need some improvements or clarifications, please feel free to suggest them.

**Comment by nehajain444** [comment]
@d78ui98 I think you should have links in readme file pointing towards wiki.

**Comment by d78ui98** [comment]
Sure @nehajain444
Also more suggestions, questions are welcomed :)

**Comment by dashohoxha** [comment]
> I think you should have links in readme file pointing towards wiki.

You can also make a pull request about this, if you wish.

**Comment by dashohoxha** [comment]
I have updated the wiki page: https://github.com/docker-scripts/dev--LTSP/wiki/LTSP-Modes-of-Operation
You can review it and make further corrections/improvements.
