### ISSUE TITLE
Tidy install.sh

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#25]
- [x] Replace `apt-get` with `apt` on `install.sh`
 - [x] Remove extra empty lines.
 - [x] Improve comments.

**Comment by dashohoxha** [comment]
I am assigning this task to @rr83019 since @CodeDem is not responding.

**Comment by rr83019** [comment]
In the blog http://dashohoxha.fs.al/ltsp-pnp/#sec-3-4, you have mentioned that Edubuntu programs can be installed in one of the two ways, but in the script install.sh both the methods are written. Should I remove one method? If yes, then which one?

**Comment by dashohoxha** [comment]
Thanks for noticing this. You can remove the first one.

**Comment by d78ui98** [comment]
@rr83019 If you wish you can work on this fixing this issue now.
