### ISSUE TITLE
Automate testing

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#26]
In order to help with testing, create the file `client/Vagrantfile` that starts automatically a client VirtualBox machine, with no disks, with bridged networking, that boots from the network. This may help a bit the testing process.

Maybe it can be done more easily with a shell script, like `client.sh`, which uses `virtualbox` commands and options.

By the way, where is the documentation of the virtualbox command-line options?

**Comment by d78ui98** [comment]
>Maybe it can be done more easily with a shell script, like client.sh, which uses virtualbox commands and options.

Yes I have created one. It is much easier to do with shell script. Working on some automating some VBoxManage commands.
>By the way, where is the documentation of the virtualbox command-line options?

I have not created its documentation. Just created a file that summarizes some of the  VBoxManage's commands.

**Comment by dashohoxha** [comment]
> I have not created its documentation. Just created a file that summarizes some of the VBoxManage's commands.

I mean where is the documentation of VBoxManage itself? Is it online? Or it is just on PDF?

**Comment by d78ui98** [comment]
its online on the virtualbox.org website - https://www.virtualbox.org/manual/ch08.html

**Comment by dashohoxha** [comment]
It says:

> With it, you can completely control VirtualBox from the command line of your host operating system. VBoxManage supports all the features that the graphical user interface gives you access to, but it supports a lot more than that. It exposes really all the features of the virtualization engine, even those that cannot (yet) be accessed from the GUI.

So, by automating things with bash scripts we can actually do more advanced things than what can be done from the GUI. This is wonderful.

**Comment by d78ui98** [comment]
Yes, it is also fast. Like really fast. I am able to setup ltsp client in an instant!
