### ISSUE TITLE
Make LTSP server a bit more flexible

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#28]
Regarding DHCP, a LTSP server has two main modes of operation: standalone and non-standalone. These depend on whether we have a DHCP server on the LAN or not. If we already have a DHCP server, then we don't want to start a second DHCP service on the LTSP box, because this may create trouble on the network. Instead, we want to use the existing DHCP service.

1. **Standalone** means that the LTSP server also provides DHCP service to the clients, and often it also acts as a gateway for the internet. In this case the LAN of the clients is isolated from the rest of the computers (that don't use LTSP), the LTSP server also is the DHCP and gateway server of the LAN, and so it also has two network interfaces (one for the LAN and one for the WAN). The WAN interface is usually configured automatically from another DHCP server, and the LAN interface usually has a static (fixed) IP address (for example `192.168.10.1/24`).

2. **Non-standalone** means that the LTSP server does not provide IP addresses (DHCP service) to the clients, but there is another (existing) DHCP server on the LAN that does this. In this case the LTSP server usually is not the gateway to the Internet, and the LTSP server only needs to have a single network interface for connecting to the LAN. This network interface must have a static (fixed) IP address, which belongs to the same network as the IP range given by the DHCP server. So, in this case we also need to know the network of the LAN (for example 192.168.10.0/24, or 192.168.11.0/24, etc.)

This task is about making the `Vagrantfile` and the `install.sh` script flexible so that they can support both of these cases. For this we need a configuration file, for example `settings.sh`, with a content like this:
```
STANDALONE=yes
NETWORK=192.168.1.0/24
LAN_IP=192.168.1.1/24
```
These settings should be loaded both by the `Vagrantfile` (which is a Ruby script) and by `install.sh` (which is a Bash script) and they should build and configure the LTSP server accordingly.

**Comment by dashohoxha** [comment]
@docker-scripts/ltsp 
I am sure that @d78ui98 can do this task himself, but if somebody would like to help, you are welcome.
Anyway, the best help in my opinion, is with testing his scripts independently. (The developer is always biased about the scripts that he makes himself).

**Comment by d78ui98** [comment]
I now understood the problem. And also why is it important to do this. Now working towards making `Vagrantfile` and the `install.sh` script flexible to handle both cases. Also I was able to solve #29 while working on this issue.

**Comment by d78ui98** [comment]
@dashohoxha  There is some issue with ubuntu `bionic` box. It is unable to offer **standalone** mode of operation. I followed instructions on http://dashohoxha.fs.al/ltsp-pnp/#sec-3-4. It is not working at all. I also wrote modified version the `install.sh` by refering to your blog post. It works great with `trusty` but does not work with `bionic`. Feel free to test it out. What should I do in this case?

**Comment by dashohoxha** [comment]
> Feel free to test it out.

How can I test it?

> What should I do in this case?

Maybe do `vagrant sh` and check why it does not work.

**Comment by d78ui98** [comment]
I did `vagrant ssh` for testing it. Here is how I tested it -
- created a `bionic` box with the Vagrantfile and install.sh
- On your [blog](http://dashohoxha.fs.al/ltsp-pnp/#sec-3-4)  instructions are simple. In `etc/dnsmasq.d/ltsp-server-dnsmasq.conf` keep the `dhcp-range` line. Comment the line with proxy in the end
- then restart the service (if changes are made in conf file)

This does not works on `bionic` only works on `trusty`
I also made a video of this - https://youtu.be/Kx9q1QQQwa4

**Comment by dashohoxha** [comment]
> This does not works on bionic only works on trusty

Have you tested on `xenial`? `trusty` is too old (2014).

Anyway, I have an idea about what you are doing wrong, but I won't tell it to you because you should learn to troubleshoot, and you should learn to google about errors, and I should be your last resort for asking help with fixing problems (after you have spent a few days and could not solve it). I can guide you and give advice, but I cannot fix your problems or do your job.

So, if you read carefully the documentation that I told you above, and follow the steps carefully, you will be able to find the problem and fix it. There is nothing wrong with `bionic`, it is you that is doing some mistake.

If that does not work, then try to google about how to debug and troubleshoot dnsmasq and dhcp on ubuntu. This is the long and hard way of solving the problem.

**Comment by d78ui98** [comment]
okay. I will try with `xenial` then will find my mistake and fix it.

**Comment by d78ui98** [comment]
Figured out my mistake :) 
>There is nothing wrong with bionic, it is you that is doing some mistake.

you were right.

**Comment by dashohoxha** [comment]
I am happy that you figured it out yourself, because it was such a silly mistake :)

**Comment by rr83019** [comment]
I've made some changes to install.sh such that it auto detects and configures the mode of operation of ltsp server. Settings.sh file can now be omitted if not required. 
I hope this makes the installation process much more user friendly.

**Comment by d78ui98** [comment]
cannot omit `settings.sh`. It is still required.

**Comment by dashohoxha** [comment]
> I've made some changes to install.sh such that it auto detects and configures the mode of operation of ltsp server.

It is not something that should be auto-detected, it should depend on the configuration (settings.sh).
If you want to do some auto-detection, then it should be done on the Vagrantfile, before the box is created and provisioned. It should not be done on `install.sh`.

**Comment by dashohoxha** [comment]
To test the **standalone** mode, I think that you need to work on a computer with two network interfaces. However most laptops have a wifi card and an ethernet (cable) card, so it should be ok.
The vagrant box is going to have two virtual interfaces, which are bridged one to the wifi and the other to the cable. Let's say that wifi will be connected to the WAN and the cable to the LAN.
In this case you also need to enable/configure NAT inside the box, so that the clients can have access to internet (through the LTSP server, which is acting as a gateway).

**Comment by d78ui98** [comment]
>In this case you also need to enable/configure NAT inside the box, so that the clients can have access to internet (through the LTSP server, which is acting as a gateway).

That is done. vagrant box has NAT configuration allowing to use commands like `vagrant up` ,etc. Same is being used by clients to access internet. Where ltsp server is acting like a gateway

**Comment by d78ui98** [comment]
this problem is this -
> For the standalone case the VM should have 2 network interfaces. For the non-standalone case it should have only one

Currently vagrant box with ltsp installed has 2 network interfaces. NAT and bridged. NAT is fundamental requirment of vagrant. And without bridged adapter ltsp server won't be able to communicate with clients. Which interfaces should be removed?

**Comment by dashohoxha** [comment]
> Currently vagrant box with ltsp installed has 2 network interfaces. NAT and bridged. NAT is fundamental requirment of vagrant. And without bridged adapter ltsp server won't be able to communicate with clients. Which interfaces should be removed?

It seems that both interfaces are required, so none of them can be removed.
OK. So the virtualbox has always 2 network interfaces (both for the standalone and non-standalone case).

> That is done. vagrant box has NAT configuration allowing to use commands like vagrant up ,etc. Same is being used by clients to access internet. Where ltsp server is acting like a gateway

The virtualbox test client should have only one network interface, the bridged one, in order to simulate a client on the LAN. In this case, I think that you need to configure NAT inside the LTSP server, so that the test client can access the internet (using LTSP server as a gateway).

I am not sure whether I am explaining it clearly and whether you understand it.

**Comment by d78ui98** [comment]
Okay, Now I get it. Virtualbox test clients will have a single interface.
