### ISSUE TITLE
DHCP server for testing

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#29]
For testing the case of a non-standalone server (see: https://github.com/docker-scripts/dev--LTSP/issues/28) we need to run a DHCP server on the network.

Create the file `dhcp/Vagrantfile` that starts automatically a virtualbox DHCP server on a bridged network. This can be a very simple server, with low RAM (for example 512MB) that provides a simple DHCP service.

The most simple way for offering a DHCP service is to install and configure **dnsmasq**.

**Comment by d78ui98** [comment]
I have created `dhcp/Vagrantfile` with ram 512MB. Created provision script to install **dnsmasq**. 
I have some ideas on how configure it too. 
For testing it should I create another ltsp server with dnsmasq not installed and start this server and ltsp client And see if it the client can get ip address?

**Comment by dashohoxha** [comment]
For testing it you can just start a ltsp-client (booting from PXE) and see if it gets an IP address.
You don't need to run a ltsp-server. No problem that the client will fail to boot immediately after getting an IP address.

**Comment by dashohoxha** [comment]
> For testing it should I create another ltsp server with dnsmasq not installed.

A ltsp-server will always have `dnsmasq` installed. But it can be configured to give DHCP service or not.

**Comment by d78ui98** [comment]
cool. good idea.
