### ISSUE TITLE
Port ubuntu-edu packages to debian

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#3]
How to port these packages to Debian?
 - ubuntu-edu-preschool
 - ubuntu-edu-primary
 - ubuntu-edu-secondary
 - ubuntu-edu-tertiary

**Comment by d78ui98** [comment]
I have created these packages for debian. Now looking into how can I upload them to debian.
Maybe I have to use [mentors.debian.net](mentors.debian.net).

**Comment by dashohoxha** [comment]
> I have created these packages for debian.

Add the code of these packages on the directory `deb/`, on the `buster` branch, so that they can be installed (inside the virtual machine) even without being uploaded to debian repositories.

**Comment by dashohoxha** [comment]
There must be a project called `debian-edu` or something like this (check these packages: `apt list debian-edu-*`).
Maybe you can propose these packages for being included on this project.

**Comment by d78ui98** [comment]
should we package binary or package source and then compile on host machine?

**Comment by dashohoxha** [comment]
> should we package binary or package source and then compile on host machine?

I am not sure. But as far as I understand, you cannot make a binary package without making a source package first.

> I have created these packages for debian.

You should know it better than me, since you have already created these packages. Just upload to the project the packages that you have created.

**Comment by akash0x53** [comment]
As far as i understand:

We need to port mentioned packages available only for Ubuntu to Debian. Each package is bundle of few utilities. For example, `ubuntu-edu-preschool`, this package recommends list of packages mentioned here https://packages.ubuntu.com/trusty/misc/ubuntu-edu-preschool

So if we look into the control file of any of this packages you find `Recommends:` where all recommended packages listed. 

```Package: ubuntu-edu-tertiary
Source: edubuntu-meta
Version: 14.03.2
Architecture: amd64
Maintainer: Edubuntu Developers <edubuntu-devel@lists.ubuntu.com>
Installed-Size: 45
Recommends: calibre, cantor, celestia-gnome, chemtool, dia-gnome, fritzing, inkscape, kalzium, kmplot, ktouch, kturtle, laby, lightspeed, lybniz, marble, melting, pencil, rocs, step, yorick
Section: metapackages
Priority: optional
Description: Tertiary Educational Application Bundle
 This package depends on all of the educational software for Tertiary grade
 level education that is fully supported by Canonical and the Edubuntu
 community.
```

So in this task @d78ui98 have to create such deb package which will install all these recommended utility. @dashohoxha Please correct me if i'm wrong.

**Comment by dashohoxha** [comment]
@akash0x53 your understanding is right. Thanks for the clarification because I am not so familiar with deb packages and I don't know how to explain it properly to @d78ui98 

Only that the packages should be renamed to `debian-edu-preschool` etc.
If all of the recommended packages are available in Debian repositories (and I believe they are), that's great. Otherwise the list of recommended packages should be customized to fit Debian.
The `Maintainer:` should be updated as well.

Building these packages should be done from control files, inside the ltsp-server, since they are not available yet on Debian repositories. But efforts should be made to submit these packages on Debian repositories as well. As far as I understand, accepting new packages on Debian repositories may take some time. Deepanshu should find the right project for submitting these packages (I believe there are some projects about education in debian).

Also, if Deepanshu wishes, he may become a part of the **Edubuntu** community (although this is an Ubuntu community). As far as I know, the development and maintenance of the **Edubuntu** project has stopped, because the original developers are not able to support it anymore (life got into their way and they don't have much time anymore). They need help from new developers.
But this is totally optional and will not influence in any way the evaluation of this GSoC project.

**Comment by d78ui98** [comment]
okay, So I will do this -
-  create source such that all recommended utilities(available) are installed. 
-  change the `Maintainer`
-  Rename them packages
-  Build packages from control files, inside the ltsp-server.
-  Lastly install them
-  will also propose these packages in debian-edu project

Please correct me if I am missing something.

**Comment by dashohoxha** [comment]
Maybe you should start by studying and learning how to create debian packages. Otherwise you will be doing trial and error (or hit and miss), and the resulting packages may not be optimal.

I suggest that you place the code related to these packages on a separate script, for example called `edu.sh`, and include it (`source` it) from the main installation script.
