### ISSUE TITLE
Document the modes of operation of the ltsp-server

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#36]
Create a document that describes (to the new users) the standalone operation mode, including also some network diagrams. Then describe also the dependent (non-standalone) operation mode, again with some diagrams.
And then a document that describes how to test each of these modes.

You can use the format markdown for these documents. It can be something similar to this: https://github.com/EasyGnuPG/ggpg/blob/describing-application/docs/description.md

For drawing network diagrams you can use Dia or some other tool that you are familiar with. I have used Dia many years ago and I have been happy with it. For example have a look at the network diagrams here:
 - https://www.researchgate.net/publication/317181126_Building_a_Gateway_Server

**Comment by dashohoxha** [comment]
You will have to notify me when you finish this document, because wiki does not send notifications.

Creating this document may help you to understand better what you need to do with the scripts (installation, testing, client, dhcp server, etc.), because I think that you are not quite clear and you are struggling a bit. So, it is like a design document for the scripts that you should build.

**Comment by d78ui98** [comment]
@dashohoxha I wrote about standalone and non-standalone mode of operation. Also wrote about manual testing. I am constantly updating it. Will write about automated testing soon after I add `vagrantfile` for dhcp.

**Comment by dashohoxha** [comment]
@d78ui98 Now that I see some diagrams the ideas become more clear even for me.

In the second case (non-standalone mode), the DHCP server should also be the gateway to internet both for the clients and for the LTSP server. So, the LTSP server in this case must have only one network interface (which is bridged). Can you update the diagram for this?

**Comment by dashohoxha** [comment]
Also, again for the non-standalone mode, we can remove the requirement for having a fixed IP address, if we automatically reconfigure the **dnsmasq** on boot, to use for dhcp proxy whatever IP the box has received from DHCP. 
I am not sure whether I am explaining it clearly what I mean.
Maybe later we can create another task for this improvement.

**Comment by d78ui98** [comment]
Updated. 
Yes. Things are now clear. I was wondering how the internet is served to clients(Non-standalone mode) But now it is clear.
>I am not sure whether I am explaining it clearly what I mean.
Maybe later we can create another task for this improvement.

I am able to understand this. Sure we will create another task for it later.

**Comment by dashohoxha** [comment]
Please update the diagrams here: https://github.com/docker-scripts/dev--LTSP/wiki/Mode-of-operation-LTSP
so that they look similar to the ones that I have drawn. Especially the LAN network, which is usually represented by a thick bar where all the computers are connected.

[nonstanalone-ltsp-server.pdf](https://github.com/docker-scripts/dev--LTSP/files/2064857/nonstanalone-ltsp-server.pdf)
[standalone-ltsp-server.pdf](https://github.com/docker-scripts/dev--LTSP/files/2064858/standalone-ltsp-server.pdf)

**Comment by d78ui98** [comment]
I just updated it on the wiki page. Thanks for the hand-drawn diagrams.

**Comment by dashohoxha** [comment]
Thanks for not getting frustrated that I am asking you to do the same things over and over again. But if they are not right we have to make them right.

**Comment by d78ui98** [comment]
No worries. I understand its important to make things right. Would be happy to do it again to make it better :)

**Comment by d78ui98** [comment]
@dashohoxha We have documented modes of operation so should we close this issue?
