### ISSUE TITLE
Automatic reconfiguration of dnsmasq on boot

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#37]
For the non-standalone mode, we can remove the requirement for having a fixed IP address, if we automatically reconfigure the dnsmasq on boot, so that it can use for dhcp proxy whatever IP the box has received from DHCP.

**Comment by d78ui98** [comment]
Akash and I want to make sure if we get this correctly.
So the goal of this task is to reconfigure server to provide dhcp services in the network in which the ltsp server belongs. For non-standalone mode.

**Comment by dashohoxha** [comment]
That's right. In this case `dnsmasq` will not offer IP (via DHCP), however it will be **proxy** dhcp server, which means that will offer tftp service and booting from network.
