### ISSUE TITLE
Create a wiki page about how to debug LTSP from a client 

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#49]
https://github.com/docker-scripts/dev--LTSP/wiki

**Comment by d78ui98** [comment]
Should I mention all the steps suggested on irc?(please note that those steps were good but not the solution to our problem)

one solution was provided by @akash0x53  and another one I figured out by looking at logs.

**Comment by d78ui98** [comment]
Should I mention all the steps suggested on irc?(please note that those steps were good but not the solution to our problem)

one solution was provided by @akash0x53 and another one I figured out by looking at logs.

**Comment by dashohoxha** [comment]
What you think is reasonable and could be useful for other people, or on other similar situations.

**Comment by d78ui98** [comment]
I wrote the wiki page - [https://github.com/docker-scripts/dev--LTSP/wiki/Troubleshooting](https://github.com/docker-scripts/dev--LTSP/wiki/Troubleshooting)
Also the blog post - [https://medium.com/@gajbhiyedeepanshu/solving-ltsp-client-not-able-to-login](https://medium.com/@gajbhiyedeepanshu/solving-ltsp-client-not-able-to-login-issue-50384c98efbc)

will be updating the trouble shoot page if I find any new issue. Most solution are from irc channel, mailing list and also from personal experience.

**Comment by dashohoxha** [comment]
You should also update the Testing page. Maybe it is better to split it into 2 pages, one for manual testing (which describes all the cases that needs to be tested), and one for automated testing.

**Comment by d78ui98** [comment]
Now that we can do automated testing in one command with `./tesh.sh start` I don't think we need a new wiki page for that.

**Comment by dashohoxha** [comment]
I think that Testing Plan does a part of the job. Troubleshooting pages, which have more detailed instructions do the rest.

Maybe some wiki pages need to be refreshed and updated a bit to reflect the latest developments.

However this task can be closed since you have written a blog post for it.

**Comment by d78ui98** [comment]
> Maybe some wiki pages need to be refreshed and updated a bit to reflect the latest developments.

Exactly. will be doing that along with https://github.com/docker-scripts/dev--LTSP/issues/64
