### ISSUE TITLE
Improve settings.sh

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#59]
- [x] Add comments on `settings.sh` that explain what each variable is used for and what values it can take.
- [x] Remove variable NETWORK because this can be derived from LAN_IP.
- [x] Make the default value of LAN_IP `="192.168.111.16"` in order to avoid that tests work accidentally (by mistake).
- [x] Rename the variable INTERFACE to LAN_IF.
- [x] Add a variable PACKAGES which has a list of extra packages that should be installed on the base ltsp-server. Here are included packages like `ubuntu-edu-preschool` etc. For testing this list can be empty, in order to shorten the time needed for installing the server.

**Comment by d78ui98** [comment]
Based on above comment I am planning to create `settings.sh` file something like this

```
# mode of operation. yes for standalone mode. no for normal mode
# refer this - https://github.com/docker-scripts/dev--LTSP/wiki/LTSP-Modes-of-Operation 
STANDALONE="yes"

# IP address of ltsp server
LAN_IP="192.168.111.16"
NETWORK="$(echo $LAN_IP | cut -d'.' -f1-3)"

# Interface used by ltsp server, client and dhcp server. 
# Will be automatically set by test.sh.
LAN_IF=""

# List of extra packages to be installed on ltsp server.
PACKAGES="vim"
 
```
this has been tested internally. also replaced `INTERFACE` with `LAN_IF` in both the `Vagrantfiles` and `test.sh` script.

**Comment by dashohoxha** [comment]
The line of NETWORK may not work on Ruby.
Add at least 2 extra packages for proper testing.
Look at the other tasks/issues in case there is anything else that needs to be added on settings.sh

**Comment by d78ui98** [comment]
I just tested NETWORK line does work well. (as stuff inside it is in double quotes)

**Comment by d78ui98** [comment]
> Look at the other tasks/issues in case there is anything else that needs to be added on settings.sh

just have to enable debugging. Something I plan on doing later when solve #58

**Comment by dashohoxha** [comment]
> I just tested NETWORK line does work well. (as stuff inside it is in double quotes)

You mean that Ruby does $ shell expansion?

> just have to enable debugging.

Do this before testing.

**Comment by d78ui98** [comment]
> You mean that Ruby does $ shell expansion?

no. `NETWORK` is not used by `Vagrantfile`. Putting it inside double quotes make it a normal ruby variable.

If I write `puts NETWORK` in vagrantfile it would print out `(echo $LAN_IP | cut -d'.' -f1-3)`. while in bash script it will do shell expansion and get network address.

**Comment by dashohoxha** [comment]
You are right. But nonetheless it defeats the purpose of a configuration file. You can do that calculation on the bash script instead.

**Comment by d78ui98** [comment]
Sure. I can do that.
