### ISSUE TITLE
LTSP server needs to have a GUI

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#60]
LTSP server is used by the teacher, so it needs to have a GUI window. For example the teacher can use `epoptes` to check what the students are doing, or to show a demonstration to them.

**Comment by d78ui98** [comment]
For this I am planning to change 2 files. `install.sh` and `Vagrantfile`
Going to add this in `Vagrantfile`
```
config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
   end
```
and in `install.sh`
`apt --yes install ubuntu-desktop` on `bionic` branch
I am testing it right now.

**Comment by dashohoxha** [comment]
Install xfce desktop instead, because with 1Gb RAM you may have performance problems with the ubuntu desktop.

**Comment by d78ui98** [comment]
yes. ubuntu-desktop does not work well at all.

**Comment by d78ui98** [comment]
`xfce` work - https://ibb.co/bQ66Uo
there were few errors - https://ibb.co/fOkN28
I googled about and fixed by it by  `apt --yes install gtk2-engines-pixbuf`

**Comment by d78ui98** [comment]
I am able to use `epoptes` and `ltsp-manager` from it. Creating a PR
