### ISSUE TITLE
Make the VagrantBox of the ltsp-server secure

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#61]
Currently the ssh service on the ltsp-server can be accessed with a key that is public. Make it secure by generating and using a new key.

**Comment by d78ui98** [comment]
I was looking into this and wondering about it. Vagrant boxes are not secure as they use a key that is public. But when we do a `vagrant up` This is the output
```
default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
```
I also found out the PR that added this functionality - https://github.com/hashicorp/vagrant/pull/4707
It randomly generates a keypair for better security. Does that mean our vagrant box is secure without generating a new key pair?
Needed to know that before pushing changes for this task

**Comment by dashohoxha** [comment]
You are right.
