### ISSUE TITLE
Improve the docs

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#64]
Improve the usage docs to show how to create a ltsp-server, how to start and stop it, how to destroy and recreate it, what to do when some settings are changed in order to make sure that these changes are reflected to the server, etc.

Right now the docs mention only `vagrant up`, which is quite insufficient for a beginner.

See also: https://github.com/docker-scripts/dev--LTSP/issues/19

**Comment by dashohoxha** [comment]
You should update the wiki pages as well, if needed.

**Comment by d78ui98** [comment]
Yes I have updated it. Removed lines that involved setting up `NETWORK` variable.
