### ISSUE TITLE
Custom vagrant box

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#68]
- [x] Build a custom vagrant box based on LinuxMint 19 Xfce. This will speed up testing and usage (when users build a new ltsp server).
   - https://www.linuxmint.com/download.php
   - https://www.vagrantup.com/docs/virtualbox/boxes.html
   - https://www.engineyard.com/blog/building-a-vagrant-box
   - https://www.skoblenick.com/vagrant/creating-a-custom-box-from-scratch/
   - http://blog.ruilopes.com/from-iso-to-vagrant-box.html
   - http://jayunit100.blogspot.com/2014/10/building-vagrant-virtualbox-box-from-iso.html

 - [x] Add a configuration variable on `settings.sh` for the vagrant base box, so that users can choose another base system (instead of LinuxMint Xfce). As long as it is an Ubuntu derivative all the provision scripts should work fine.

- [x] Write a blog or wiki page about how to build a custom vagrant box for the ltsp-server, so that the users can use another flavor of Ubuntu for their ltsp server.

**Comment by d78ui98** [comment]
I have created a linux mint vagrant box. 
Wrote a blog post as well -https://medium.com/@gajbhiyedeepanshu/building-custom-vagrant-box-e6a846b6baca
Just need to confirm what needs to be done for the last task. So I need to create a configuration variable `box` in `settings.sh`. Where user can mention the box name. This value will be assigned to `config.vm.box` in `Vagrantfile`?
Needed to confirm this before pushing changes.

**Comment by dashohoxha** [comment]
> Just need to confirm what needs to be done for the last task. So I need to create a configuration variable box in settings.sh. Where user can mention the box name. This value will be assigned to config.vm.box in Vagrantfile?
Needed to confirm this before pushing changes.

This is correct. You can call the variable `VM_BOX` or something like this. While you are at it, you can allow the user to set the size of the memory as well. For example you can add a variable like this: `VM_RAM="1024"`.

**Comment by dashohoxha** [comment]
> I have created a linux mint vagrant box.
Wrote a blog post as well -https://medium.com/@gajbhiyedeepanshu/building-custom-vagrant-box-e6a846b6baca

Nice job. I have a few suggestions.
 - [x] First of all, check it again for any typing mistakes or any formatting errors.
 - [x] Have you tried to install Vagrant and VirtualBox from the terminal? I see some packages related to them (for example if you try: `apt list vagrant*` and `apt list virtualbox*`). When you give command-line instructions, these are easier for readers to follow (with copy/paste), and less error-prone than GUI instructions.
 - [x] The name of the virtual machine and the vagrant box should be something more specific, for example: `linuxmint19-xfce-32bit`.
 - [x] Is there some repository where you can publish vagrant boxes, so that the user does not have to build it himself but just download and use it? This would be a great help for not-so-technical users.
 - [ ] Even if the request above works and you have published the linuxmint19 vagrant box somewhere, is it possible to automate the process of building a new vagrant box, so that a user just downloads a settings file (or a template) and builds the vagrant box from it automatically, without having to go through the manual GUI process? This would also be very useful and a great help for the users and developers. If you can find such an automatic process for building the required vagrant box, then publishing somewhere the vagrant box itself becomes not so important, since everybody can build it locally with a single command or script.
 - [x] After you solve all these issues, maybe you can also write a wiki page similar to the blog page, that describes how to build vagrant boxes.

**Comment by akash0x53** [comment]
My suggestions,

1. Remove `apt` or `yum` cache or remove anything that is temporary to reduce box size. Refer [this](https://github.com/chef/bento/blob/82752ec/packer/scripts/ubuntu/cleanup.sh) script to know more what items you purge.
2. You can upload your box here https://app.vagrantup.com/boxes/search

**Comment by d78ui98** [comment]
> remove anything that is temporary to reduce box size

Nice this is good.

**Comment by d78ui98** [comment]
> is it possible to automate the process of building a new vagrant box

We can use [packer](https://www.packer.io/)

> You can upload your box here https://app.vagrantup.com/boxes/search

By taking that script as reference I created my own script. Ran that on virtual machine and reduced its size and creation time. I can upload it on vagrant cloud.
After upload name to put in Vagrantfile will be `d78ui98/linuxmint19-xfce-32bit`
Should I shorten name to `mintxfce32`?
As on the website they said
````
The name of your Vagrant box is used in tools, notifications, routing, and this UI. Short and simple is best.
````

**Comment by dashohoxha** [comment]
> We can use packer

This looks good. Maybe it can do what we want: https://www.packer.io/docs/builders/virtualbox-iso.html
Please figure out how to do it.

> After upload name to put in Vagrantfile will be `d78ui98/linuxmint19-xfce-32bit`
Should I shorten name to `mintxfce32`?

Actually I think that it should be `linuxmint-19-xfce-32bit` in order to be as clear as possible (this is the same as the name of the `.iso` file).

However `d78ui98/` may seem a bit strange to people. Can you create an account with the name `linuxmint/`? Maybe you should ask permission from the LinuxMint community first.

Then to shorten the name a bit you can use the codename `Tara` (`=linuxmint-19`).
So you can create 6 boxes like this: `linuxmint/tara32` (cinnamon), `linuxmint/tara64` (cinnamon), `linuxmint/tara32-xfce`, `linuxmint/tara64-xfce`, `linuxmint/tara32-mate`, `linuxmint/tara64-mate`.
If you create a script to automatically create one of them (`tara32-xfce`), it should be very easy to create automatically all the rest of them.

**Comment by d78ui98** [comment]
Sure we can do this. However, it will take time even with script I have to download the remaining 5 iso(1.9gb each). Create box for each. Upload all 6 on cloud(2.6gb each). 
I will start by getting permission from linux mint community. Then work on the script.

**Comment by dashohoxha** [comment]
Maybe you should contact directly `root@linuxmint.com` to explain what you want to do and to ask for permission (https://linuxmint.com/contactus.php). You can put me and Akash on the Cc if you wish.

Then you can upload first `linuxmint/tara32-xfce` which is directly needed for testing.

Later you can continue working with automating scripts.

And finally (lowest priority) build and upload the other 5 images. You can do it a bit later, after testing is finished.

**Comment by dashohoxha** [comment]
@d78ui98 You can upload on your account the image that you have already built. Name it `linuxmint-19-xfce-32bit` (no problem that it is a bit log, it is only for testing and only temporary, until the official images are built and uploaded).

Then continue with the automating scripts, and as soon as they are ready we are going to suggest them to the LinuxMint community.

**Comment by d78ui98** [comment]
I have uploaded to box to my account - https://app.vagrantup.com/d78ui98/boxes/linuxmint-19-xfce-32bit
I also released a second version in which I reduced the size of the box significantly.

**Comment by dashohoxha** [comment]
Great!
Change also the default value on `settings.sh` to this one, and remove the line that installs the xfce desktop from `install.sh`.
Then complete all the steps of internal testing and identify any things that need to be fixed or improved. Only after that continue with automating scripts etc.

**Comment by d78ui98** [comment]
Sure. 
There are other changes to make as well. 
- `apt` not working with options provided like `--yes --install-recommends `. Have to replace with  `apt-get` - https://forums.linuxmint.com/viewtopic.php?f=47&p=1487558
- Fix dnsmasq package not working problem
- trying to find other problems

Please note it is not a problem with vagrant box that we created. But with the linux mint 19 itself.

**Comment by dashohoxha** [comment]
There is no problem with `apt` or with LinuxMint.

> There are other changes to make as well.

Make the changes one by one, and create a task for each of them.

**Comment by d78ui98** [comment]
You are right. Neither is the problem with vagrant box. Just had to change the position of the command.
But `dnsmasq` is conflicting with `systemd-resolve`. working on that

**Comment by d78ui98** [comment]
`dnsmasq` issue is fixed. I am able to boot from client.
But I am not able see any gui on client. I followed the debugging methods on ltsp.org. But none of the mentioned solutions worked.

**Comment by dashohoxha** [comment]
You can start a PR and make commits and comments on that.
Because I don't understand your comments, I don't know what you are doing and what is going on, and I am not able to help you. So, unless you can show your code, you can keep your progress comments for yourself.

**Comment by d78ui98** [comment]
I have fixed all the issues.
Also wrote wiki page about building vagrant box
https://github.com/docker-scripts/dev--LTSP/wiki/Building-Custom-Vagrant-box

**Comment by dashohoxha** [comment]
This is great.
Now you can close this issue and continue with internal testing. Identify things that do not work and create issues for them.
