### ISSUE TITLE
Get familiar with building ubuntu/debian packages

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#7]
You may have to port some packages from ubuntu to debian, or maybe to create some new packages.

1. Find some good tutorials about how to create and submit debian packages.
2. Find the relevant mailing lists about creating and maintaining debian packages and subscribe to them.

Report the results of your findings as comments.

**Comment by d78ui98** [comment]
Here are some very good resources that I found -
- https://wiki.debian.org/Packaging 
- https://www.debian.org/doc/manuals/packaging-tutorial/packaging-tutorial.en.pdf
- https://wiki.debian.org/SimpleBackportCreation
- https://www.debian.org/doc/manuals/maint-guide/upload.en.html
- https://wiki.debian.org/HowToPackageForDebian

Here is the list of relevent and active mailing lists -
- https://lists.debian.org/debian-cross/
- https://lists.debian.org/debian-input-method/
- https://lists.debian.org/deity/
- https://lists.debian.org/debian-common-lisp/
- https://lists.debian.org/debian-haskell/
- https://lists.debian.org/debian-openstack/

**Comment by dashohoxha** [comment]
Focus on closing the pending tasks first.

**Comment by dashohoxha** [comment]
I find this tutorial very nice and interesting and describing what we need to do for this project: building deb packages for internal use, without submitting them to Debian repositories:
http://tldp.org/HOWTO/html_single/Debian-Binary-Package-Building-HOWTO/

**Comment by dashohoxha** [comment]
I also find these tutorial interesting (although they are a bit old, and I am not sure if they are still relevant):
- http://terokarvinen.com/2011/create-deb-metapackage-in-5-minutes
- https://debian-handbook.info/browse/stable/sect.building-first-package.html
- https://eric.lubow.org/2010/creating-dummy-packages-on-debian/
