### ISSUE TITLE
Create scripts to automatically build vagrant boxes

### ISSUE THREAD

**Issue by d78ui98** [docker-scripts/dev--LTSP#77]
Make use of packer builds vagrant box automatically, without having to go through the manual GUI process
https://www.packer.io/docs/builders/virtualbox-iso.html

**Comment by d78ui98** [comment]
how should I upload the packer template to create vagrant box?
should I create a separate branch or something else?

**Comment by dashohoxha** [comment]
Create a sub-directory `packer/`, or something like this.
