### ISSUE TITLE
Update virtual LTSP server project to new version of LTSP

### ISSUE THREAD

**Issue by d78ui98** [docker-scripts/dev--LTSP#85]
First tested LTSP version for `Ubuntu 18.04` is is released. Many bugs are fixed. 
Update virtual ltsp server project for the same.
https://sourceforge.net/p/ltsp/mailman/message/36369066/

**Comment by dashohoxha** [comment]
By the way, try to test GUESTLOGIN and AUTOLOGIN as soon as possible, so that you can ask Alkis in case that something does not work.

**Comment by d78ui98** [comment]
`AUTOLOGIN` works just tested. Now checking for `GUESTLOGIN`

**Comment by d78ui98** [comment]
`GUESTLOGIN` also works.
