### ISSUE TITLE
release new version of linux mint vagrant box

### ISSUE THREAD

**Issue by d78ui98** [docker-scripts/dev--LTSP#89]
The vagrant box should be updated every month to ensure having the latest packages.

**Comment by dashohoxha** [comment]
> The vagrant box should be updated every month to ensure having the latest packages.

I don't agree. You need to generate a new box only when LinuxMint makes a new release.

**Comment by d78ui98** [comment]
Yes. But in this version I was able to do 2 tasks
- reduce size of box
- also dist-upgrade(inorder to remove Debian frontend variable from `apt upgrade`)

Thats why released a new version.
There is no definite answer about how often vagrant box should be updated. However boxes like `bionic64` are updated very often.
https://app.vagrantup.com/ubuntu/boxes/bionic64
